# Generated by Django 4.2 on 2025-04-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServiceProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image_url',
            field=models.URLField(blank=True, default='media/profile_images/default.png'),
        ),
    ]
