# Generated by Django 4.2 on 2025-03-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFAServiceProject', '0002_device_remove_twofactorauth_is_verified_once_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
