# Generated by Django 4.2 on 2025-03-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFAServiceProject', '0003_twofactorauth_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
