# Generated by Django 4.2 on 2025-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFAServiceProject', '0004_alter_twofactorauth_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
