# Generated by Django 4.2 on 2025-03-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFAServiceProject', '0005_alter_twofactorauth_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
